---
apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/port: "9779"
    prometheus.io/scrape: "true"
  labels:
    expose: "true"
    provider: fabric8
    project: fis-camel-spring-boot-demo
    version: 1.0-SNAPSHOT
    group: net.atos
  name: fis-camel-spring-boot-de
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    project: fis-camel-spring-boot-demo
    provider: fabric8
    group: net.atos
