---
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/port: "9779"
      prometheus.io/scrape: "true"
    labels:
      expose: "true"
      provider: fabric8
      project: fis-camel-spring-boot-demo
      version: 1.0-SNAPSHOT
      group: net.atos
    name: fis-camel-spring-boot-de
  spec:
    ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
    selector:
      project: fis-camel-spring-boot-demo
      provider: fabric8
      group: net.atos
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    annotations:
      fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fis-camel-spring-boot-demo&var-version=1.0-SNAPSHOT
    labels:
      provider: fabric8
      project: fis-camel-spring-boot-demo
      version: 1.0-SNAPSHOT
      group: net.atos
    name: fis-camel-spring-boot-de
  spec:
    replicas: 1
    selector:
      project: fis-camel-spring-boot-demo
      provider: fabric8
      group: net.atos
    template:
      metadata:
        annotations:
          fabric8.io/metrics-path: dashboard/file/camel-routes.json/?var-project=fis-camel-spring-boot-demo&var-version=1.0-SNAPSHOT
        labels:
          provider: fabric8
          project: fis-camel-spring-boot-demo
          version: 1.0-SNAPSHOT
          group: net.atos
      spec:
        containers:
        - env:
          - name: KUBERNETES_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          image: atos/fis-camel-spring-boot-demo:snapshot-170918-162415-0646
          imagePullPolicy: IfNotPresent
          livenessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 180
          name: spring-boot
          ports:
          - containerPort: 8080
            name: http
            protocol: TCP
          - containerPort: 9779
            name: prometheus
            protocol: TCP
          - containerPort: 8778
            name: jolokia
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /health
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 10
          resources:
            limits:
              cpu: "1.0"
            requests:
              cpu: "0.2"
          securityContext:
            privileged: false
    triggers:
    - type: ConfigChange
